spring:

  profiles:
    active: dev

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useServerPrepStmts=true&cachePrepStmts=true&useSSL=false
    username: root
    password: 000000
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      clear-filters-enable: true
      max-active: 20
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      filters: stat

  jpa:
    properties:
      hibernate:
        ddl-auto: update
      show-sql: true

  redis:
    host: 127.0.0.1
    port: 7008
    password: 123456
    jedis:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 0
        max-wait: 2000ms
    timeout: 3000ms

  cache:
    type: redis
    redis:
      time-to-live: 2m
      key-prefix: true

  rabbitmq:
    addresses: "localhost"
    port: 5672
    connection-timeout: 3s


server:
  port: 8080

## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapper/*.xml #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.ximuyi.demo.mybatis.model # 注意：对应实体类的路径

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

jim:
  name: Jim
  age: 12
  number:  ${random.int}
  uuid : ${random.uuid}
  max: ${random.int(10)}
  value: ${random.value}
  greeting: hi,i'm  ${jim.name}